# Generated by Django 5.2.4 on 2025-08-01 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoundItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('Description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='lost_images/')),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('contact_info', models.CharField(max_length=100)),
                ('date_found', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LostItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='lost_images/')),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('contact_info', models.CharField(max_length=100)),
                ('date_lost', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
